--数据库命令行打开初始化语句,方便格式化直观显示
sqlplus scott/tiger
ALTER SESSION SET NLS_DATE_FORMAT='YYYY-MM-DD HH24:MI:SS'  ;
SET LINESIZE 300 
SET PAGESIZE 30
COL TNAME FOR A40
CLEAR SCR 
COL TEACHER_NAME FOR A20
COL CLAZZ_NAME FOR A20
COL COURSE_NAME FOR A30
COL NOTE FOR A40
COL SEQUENCE_NAME FOR A40
COL MAJOR_NAME FOR A20
COL PASSWORD FOR A20
COL STUDENT_NAME FOR A30
COL STUDENT_ID FOR A30
